apiVersion: cw.com/v1
kind: ApiGateway
metadata:
  name: christians-apigateway2
spec:
  serviceLabel: labelOfServicesThatHAveTobeAddedToIngress
  backend:
    serviceName: lumpensammler
    servicePort: 8080
  rules:
  - http:
      paths:
      - path: /ausschluss
        backend:
          serviceName: ausschluss-service
          servicePort: 10001
