required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.10"
