apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apigateways.cw.com
spec:
  scope: Namespaced
  group: cw.com
  version: v1alpha
  names:
    kind: ApiGateway
    singular: apigateway
    plural: apigateways
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceLabel:
              type: string
